CREATE TABLE IF NOT EXISTS {}.categories (
  id INT(12) NOT NULL AUTO_INCREMENT PRIMARY KEY,

  name VARCHAR(30) NOT NULL,
  description VARCHAR(300) NOT NULL,
  slug VARCHAR(30) NOT NULL,


  FULLTEXT slug_search(slug),

  UNIQUE (slug)
)
ENGINE=InnoDB;